vgginternship/projects/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, BooleanField, TextAreaField
from wtforms.validators import DataRequired, Length, Email, EqualTo ,ValidationError





class projectForm(FlaskForm):
    Projectname = StringField('Projectname', validators=[DataRequired()])
    description = TextAreaField('description', validators=[DataRequired()])
    submit = SubmitField('Add new project')

class actionForm(FlaskForm):
    description = TextAreaField('description', validators=[DataRequired()])
    note = TextAreaField('note', validators=[DataRequired()])
    submit = SubmitField('Add')

class updateActionForm(FlaskForm):
    description = TextAreaField('description', validators=[DataRequired()])
    note = TextAreaField('note', validators=[DataRequired()])
    submit = SubmitField('Update Action')

vgginternship/main/routes.py
from flask import render_template, url_for, flash,redirect, request, Blueprint

main = Blueprint('main', __name__)



@main.route('/')
@main.route('/home')
def home(): 
    return render_template('index.html')

vgginternship/projects/routes.py
from flask import render_template, url_for, flash,redirect, request, Blueprint
from vgginternship.extensions import  bcrypt, db
from vgginternship.models import User, Projects, Actions
from flask_login import  current_user, login_required
from vgginternship.projects.forms import projectForm, actionForm, updateActionForm

projects = Blueprint('projects', __name__)




@projects.route('/project')
@login_required
def project():
    page = request.args.get('page', 1, type = int)
    projects = Projects.query.paginate(page = page, per_page=3)
    return render_template('project.html', projects=projects)

@projects.route('/project/new', methods = ['GET', 'POST'])
@login_required
def new_project(): 
    form = projectForm()
    if form.validate_on_submit():
        project = Projects(name= form.Projectname.data, description = form.description.data)
        db.session.add(project)
        db.session.commit()
        flash('post created', 'success')
        return redirect(url_for('projects.project'))
    return render_template('newProject.html', form = form)



@projects.route('/project/<int:project_id>')
@login_required
def projectz(project_id):
    project = Projects.query.get_or_404(project_id)
    return render_template('projectid.html', project=project)


@projects.route('/project/<int:project_id>/update', methods=['GET', 'POST'])
@login_required
def updateProject(project_id):
    project = Projects.query.get_or_404(project_id)
    form = projectForm()
    if form.validate_on_submit():
        project.name = form.Projectname.data
        project.description = form.description.data
        db.session.commit()
        flash('Updated', 'success')
        return redirect(url_for('projects.projectz', project_id=project.id))
    elif request.method == 'GET':   
        form.Projectname.data = project.name
        form.description.data = project.description
    return render_template('newProject.html', form = form)

@projects.route('/project/<int:project_id>/delete', methods=['POST', 'GET'])
@login_required
def deleteProject(project_id):
    Projects.query.filter_by(id = project_id).delete()
    db.session.commit()
    flash('Deleted', 'success')
    return redirect(url_for('projects.project'))

@projects.route('/project/<int:project_id>/addActions', methods=['POST', 'GET'])
@login_required
def addActions(project_id):
    form = actionForm()
    project = Projects.query.get_or_404(project_id)
    if form.validate_on_submit():
        action = Actions(project_id = project.id, description = form.description.data, note = form.note.data)
        db.session.add(action)
        db.session.commit()
        flash('action created', 'success')
        return redirect(url_for('projects.project'))
    return render_template('addAction.html', form = form)

@projects.route('/project/actions', methods=['POST', 'GET'])
@login_required
def allActions():
    actions = Actions.query.all()
    return render_template('allActions.html', actions=actions)

@projects.route('/project/actions/<int:action_id>')
@login_required
def allActionsId(action_id):
    action = Actions.query.get_or_404(action_id)
    return render_template('singleActionId.html', action=action)


@projects.route('/project/<int:project_id>/action')
@login_required
def specificActions(project_id):
    actions = Actions.query.filter_by(project_id = project_id)
    return render_template('specificActions.html', actions=actions)


@projects.route('/project/<int:project_id>/action/<int:action_id>')
@login_required
def specificActionsId(project_id, action_id):
    action = Actions.query.get(action_id)
    return render_template('specificActionsId.html', action=action)


@projects.route('/project/<int:project_id>/action/<int:action_id>/update', methods=['GET', 'POST'])
@login_required
def updateActions(project_id, action_id):
    action = Actions.query.get_or_404(action_id)
    form = updateActionForm()
    if form.validate_on_submit():
        action.description = form.description.data
        action.note = form.note.data
        db.session.commit()
        flash('Action updated', 'success')
        return redirect(url_for('projects.specificActionsId', project_id = action.project_id, action_id = action.id))
    elif request.method == 'GET':   
        form.description.data = action.description
        form.note.data = action.note
    return render_template('updateActions.html', form = form)

@projects.route('/project/<int:project_id>/action/<int:action_id>/delete', methods=['POST', 'GET'])
@login_required
def deleteAction(project_id, action_id):
    project = Projects.query.get_or_404(project_id)
    Actions.query.filter_by(id = action_id).delete()
    db.session.commit()
    flash('Deleted', 'success')
    return redirect(url_for('projects.specificActions', project_id = project.id))

vgginternship/users/routes.py
from flask import render_template, url_for, flash,redirect, request, Blueprint, current_app
from vgginternship.extensions import  bcrypt, db
from vgginternship.models import User, Projects, Actions
from flask_login import login_user, current_user, logout_user, login_required 
from vgginternship.users.forms import registerForm, loginForm, updateAccountForm


users = Blueprint('users', __name__)



@users.route('/account', methods = ['GET', 'POST'])
@login_required
def account():
    form = updateAccountForm()
    if form.validate_on_submit():
        current_user.username = form.username.data
        db.session.commit()
        flash('your account has been updated', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
    return render_template('account.html', form = form)



@users.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated: 
        return redirect(url_for('projects.project'))
    form = loginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username = form.username.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user)
            return redirect(url_for('projects.project'))
        else:
            flash('Invalid username or password', 'warning')
    return render_template('login.html', form = form)

@users.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated: 
        return redirect(url_for('projects.project'))
    form = registerForm()
    if form.validate_on_submit():
        hashPassword = bcrypt.generate_password_hash(form.password.data)
        user = User(username = form.username.data, password = hashPassword)
        db.session.add(user)
        db.session.commit()
        flash(f'Your account has been created !', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', form = form)

@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('users.login'))

vgginternship/templates/account.html
{% extends "layout.html" %}
    {% block content %}
        <div class="container">
        <div class="content-session mt-3">
            <div class="media">
                <div class="media-body">
                    <h3 class="account-heading">
                        {{current_user.username}}
                    </h3>
                </div>
            </div>
                                  <div class="card card-form m-3" >
                                      <div class="card-body m-4 ">
                                          <form id="submitForm" method="POST"  action="">
                                              {{ form.hidden_tag() }}
                                            <fieldset class="form-group">
                                                 <div class="form-group">
                                                     {{form.username.label(class = 'form-control-label')}}
                                                     {% if form.username.errors %}
                                                     {{form.username(class = 'form-control form-control-lg is-invalid')}}
                                                      <div class="invalid-feedback">
                                                          {% for error in form.username.errors %}
                                                              <span>{{ error }}</span>
                                                          {% endfor %}
                                                      </div>
                                                     
                                                     {% else %}
                                                     {{form.username(class = 'form-control form-control-lg')}}
                                                     {% endif %}
                                                 </div> 
                                            </fieldset>
                                            <div class="form-group">
                                                {{form.submit(class="btn btn-outline-info")}}
                                            </div>
                                          </form>
                                      </div>
                                  </div>
                                  </div>
                                </div>
             
    {% endblock content %}

vgginternship/templates/addAction.html
{% extends "layout.html" %}
{% block content %}
  <div class="container">
                    <div class="card-header mt-4 text-center font-weight-bold">
                            Add action
                      </div>
                    <div class="card card-form m-3" >
                        <div class="card-body m-4 ">
                            <form id="submitForm" method="POST"  action="">
                                {{ form.hidden_tag() }}
                              <fieldset class="form-group">
                                   
                                    <div class="form-group">
                                        {{form.description.label(class = 'form-control-label')}}
                                        {% if form.description.errors %}
                                       {{form.description(class = 'form-control form-control-lg is-invalid')}}
                                        <div class="invalid-feedback">
                                            {% for error in form.description.errors %}
                                                <span>{{ error }}</span>
                                            {% endfor %}
                                        </div>
                                       
                                       {% else %}
                                       {{form.description(class = 'form-control form-control-lg')}}
                                       {% endif %}
                                    </div>  
                                    <div class="form-group">
                                            {{form.note.label(class = 'form-control-label')}}
                                            {% if form.note.errors %}
                                            {{form.note(class = 'form-control form-control-lg is-invalid')}}
                                             <div class="invalid-feedback">
                                                 {% for error in form.note.errors %}
                                                     <span>{{ error }}</span>
                                                 {% endfor %}
                                             </div>
                                            
                                            {% else %}
                                            {{form.note(class = 'form-control form-control-lg')}}
                                            {% endif %}
                                        </div>
                              </fieldset>
                              <div class="form-group">
                                  {{form.submit(class="btn btn-outline-info")}}
                              </div>
                            </form>
                        </div>
                    </div>

      </div>
{% endblock content %}

vgginternship/templates/allActions.html
{% extends "layout.html" %}
    {% block content %}
        {% for action in actions %}
          
        <div class="container">
                <div class="card my-4">
                        <div class="card text-center card-header">
                               <h4> {{action.name.name}} </h4>
                        </div>
                <div class="card card-body">
                                <label class="font-weight-bold" for="description">Description: </label>
                                <p>{{action.description}}</p>
                                    <label class="font-weight-bold" for="Note">Note: </label>
                                            <p>{{action.note}}</p>
                                        </div>
                        <div class="card card-footer">
                                <div class="form-group">
                                        <a class="form-control text-center btn btn-primary" href="{{url_for('projects.allActionsId', action_id = action.id)}}">View Actions</a>
                                </div>
                        </div>
                                </div>
                                
                              </div>
        {% endfor %}  
    {% endblock content %}

vgginternship/templates/index.html
    {% extends "layout.html" %}
    {% block content %}
    <div class="home">
        <div class="overlay">
            <div class="container">
                <div class="jumbotron text-center">
                    <a class="btn " href="{{ url_for('projects.project') }}">
                        View Projects
                    </a>
                </div>
            </div>
            </div>
        </div>
    {% endblock content %}

vgginternship/templates/layout.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="{{url_for('static', filename ='style.css')}}">
    <title>VGG Intership</title>
  </head>
  <body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light font-weight-bold">
                <a class="navbar-brand" href="/">VGG Challenge</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                  <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                  <ul class="navbar-nav">
                    <li class="nav-item ">
                      <a class="nav-link" href="{{ url_for('main.home') }}">Home <span class="sr-only">(current)</span></a>
                    </li>
                    
                    {% if current_user.is_authenticated %}
                      <li class="nav-item dropdown">
                          <a class="nav-link dropdown-toggle" href="{{ url_for('projects.project') }}" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Projects
                          </a>
                          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                              <a class="dropdown-item" href="{{ url_for('projects.project') }}">Project</a>
                            <a class="dropdown-item" href="{{ url_for('projects.new_project') }}">New project</a>
                            <a class="dropdown-item" href="{{ url_for('projects.allActions') }}">Actions</a>
                            

                        </li>
                      
                        <li class="nav-item dropdown float-right">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                              {{current_user.username}}
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                              <a class="dropdown-item" href="{{ url_for('users.logout') }}">logout</a>
                              <a class="dropdown-item" href="{{ url_for('users.account') }}">Account info</a>
                              
                          </li>
                    {% else %}
                    <li class="nav-item">
                      <a class="nav-link" href="{{ url_for('users.register')}}">Sign up</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('users.login') }}">Login</a>
                      </li>
                    {% endif %}
                  </ul>
                </div>
              </nav>
              
          {% with messages = get_flashed_messages(with_categories=true) %}
                {% if messages %}
                        {% for category, message in messages %}
                        <div class="container">
                            <div class="alert text-center alert-{{category}} mt-3">
                                    {{ message }}
                            </div>
                            </div>
                        {% endfor %}
                {% endif %}
          {% endwith %}
        {% block content %}

        {% endblock %}
        
        <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
       
    </body>
    </html>

vgginternship/templates/login.html
{% extends "layout.html" %}
    {% block content %}
      <div class="container">
                        <div class="card-header mt-3 text-center font-weight-bold">
                                Login
                          </div>
                        <div class="card card-form m-3" >
                            <div class="card-body m-4 ">
                                <form id="submitForm" method="POST"  action="">
                                    {{ form.hidden_tag() }}
                                  <fieldset class="form-group">
                                       <div class="form-group">
                                           {{form.username.label(class = 'form-control-label')}}
                                           {% if form.username.errors %}
                                           {{form.username(class = 'form-control form-control-lg is-invalid')}}
                                            <div class="invalid-feedback">
                                                {% for error in form.username.errors %}
                                                    <span>{{ error }}</span>
                                                {% endfor %}
                                            </div>
                                           
                                           {% else %}
                                           {{form.username(class = 'form-control form-control-lg')}}
                                           {% endif %}
                                       </div>
                                        <div class="form-group">
                                                {{form.password.label(class = 'form-control-label')}}
                                                {% if form.password.errors %}
                                           {{form.password(class = 'form-control form-control-lg is-invalid')}}
                                            <div class="invalid-feedback">
                                                {% for error in form.password.errors %}
                                                    <span>{{ error }}</span>
                                                {% endfor %}
                                            </div>
                                           
                                           {% else %}
                                           {{form.password(class = 'form-control form-control-lg')}}
                                           {% endif %}
                                            </div>
                                  </fieldset>
                                  <div class="form-group">
                                      {{form.submit(class="btn btn-outline-info")}}
                                  </div>
                                </form>
                                <div class="float-right">
                                        <a class="text-secondary" href="{{ url_for('users.register') }}">Wanna sign up?</a>
                                </div>
                            </div>
                        </div>
          </div>
{% endblock content %}

vgginternship/templates/project.html
{% extends "layout.html" %}
    {% block content %}
        {% for project in projects.items %}
        <div class="container">
            <div class="card mt-4">
              <div class="card card-header text-center">
                  <a href="{{ url_for('projects.projectz', project_id = project.id) }}"><h3>{{project.name}}</h3></a>
              </div>
              <div class="card card-body">
                  <p>{{project.description}}</p>
              </div>
              <div class="card card-footer">
                <div class="form-group">
                  <a class="form-control mb-2 text-center btn btn-primary" href="{{ url_for('projects.updateProject', project_id = project.id) }}">Update</a>
                  <button type="button" data-toggle="modal" data-target="#deleteModal" class="btn btn-danger btn-sm form-control">Delete</button>
                  </div>
              </div>
            </div>
            
            <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby=deleteModalLabel" aria-hidden="true">
                    <div class="modal-dialog" role="document">
                      <div class="modal-content">
                        <div class="modal-header">
                          <h5 class="modal-title" id="deleteModalLabel">Modal title</h5>
                          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                          </button>
                        </div>
                        <div class="modal-body">
                              Are you sure you want to delete?
                        </div>
                        <div class="modal-footer">
                          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                          <form method="POST" action="{{ url_for('projects.deleteProject', project_id = project.id )}}">
                                <input type="submit" class="btn btn-danger" value="Delete">
                          </form>
                        </div>
                      </div>
                    </div>
                  </div>
                  </div>
        {% endfor %}
        {% for page_num in projects.iter_pages(left_edge = 1, right_edge = 1, left_current=1, right_current = 1) %}
            {% if page_num %}
                  {% if projects.page == page_num %}
                  <a class="btn btn-info m-2" href="{{ url_for('projects.project', page=page_num)  }}">{{page_num}}</a>
                    {% else %}
                    <a class="btn btn-outline-info m-2" href="{{ url_for('projects.project', page=page_num)  }}">{{page_num}}</a>
                  {% endif %}
            {% else %}
                  ...
                {% endif %}
        {% endfor %}
        
    {% endblock content %}

vgginternship/templates/projectid.html
{% extends "layout.html" %}
    {% block content %}
    <div class="container">
            
                <div class="card mt-4">
                                <div class="card card-header text-center">
                                    <h3>{{project.name}}</h3>
                                </div>
                                <div class="card card-body">
                                    <p>{{project.description}}</p>
                                </div>
                                <div class="card card-footer text-center">
                                        <div class="form-group">
                                                <a class="btn btn-secondary form-control" href="{{url_for('projects.specificActions', project_id = project.id)}}">view actions</a>
                                </div>
                                        <div class="form-group">
                                                        <a class="btn btn-primary form-control" href="{{url_for('projects.addActions', project_id = project.id)}}">add action</a>
                                        </div>
                                        
                                </div>
                              </div>
    {% endblock content %}

vgginternship/templates/singleActionId.html
{% extends "layout.html" %}
    {% block content %}
       

        <div class="container">
                <div class="card mt-4">
                  <div class="card card-header text-center">
                      <h4>{{action.name.name}}</h4>
                  </div>
                  <div class="card card-body">
                        <label class="font-weight-bold" for="description">Description: </label>
                        <p>{{action.description}}</p>
                            <label class="font-weight-bold" for="Note">Note: </label>
                                    <p>{{action.note}}</p>
                                </div>
                        </div>
                  </div>
                </div>
    

    {% endblock content %}

vgginternship/templates/specificActionsId.html
{% extends "layout.html" %}
    {% block content %}
        
    <div class="container">
            
                <div class="card mt-4">
                    <div class="card text-center card-header">
                        <h4>{{action.name.name}}</h4>
                    </div>
                                <div class="card card-body">
                                        <label class="font-weight-bold" for="description">Description: </label>
                                        <p>{{action.description}}</p>
                                            <label class="font-weight-bold" for="Note">Note: </label>
                                                    <p>{{action.note}}</p>
                                                </div>
                                <div class="card card-footer">
                                    <div class="form-group">
                                            <a class="form-control mb-2 text-center btn btn-primary" href="{{url_for('projects.updateActions', project_id = action.project_id, action_id = action.id)}}">Update action</a>
                                            <button type="button" data-toggle="modal" data-target="#deleteActionModal" class="btn btn-danger btn-sm form-control">Delete</button>
                                    </div>
                                </div>
                                
                                
                              </div>

                              <div class="modal fade" id="deleteActionModal" tabindex="-1" role="dialog" aria-labelledby=deleteActionModalLabel" aria-hidden="true">
                                    <div class="modal-dialog" role="document">
                                      <div class="modal-content">
                                        <div class="modal-header">
                                          <h5 class="modal-title" id="deleteActionModalLabel">Modal title</h5>
                                          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                          </button>
                                        </div>
                                        <div class="modal-body">
                                              Are you sure you want to delete?
                                        </div>
                                        <div class="modal-footer">
                                          <button type="button" class="btn btn-secondary" data-dismiss="modal">No</button>
                                          <form method="POST" action="{{ url_for('projects.deleteAction', project_id = action.project_id, action_id = action.id )}}">
                                                <input type="submit" class="btn btn-danger" value="Delete">
                                          </form>
                                        </div>
                                      </div>
                                    </div>
                                  </div>
                                  </div>
        
    {% endblock content %}